#!/usr/bin/env python3
"""
Download the IBM Plex subsets the app uses and generate fonts/fonts.css.

Self-hosting is needed so the Android app can bundle the fonts into the APK
(otherwise the WebView needs a live network on first launch just to render
text) and so the website has one less third-party request.

IBM Plex Sans is a variable font: Google serves ONE file per subset covering
the whole 400-700 weight range, so weights are collapsed into a single
@font-face with a weight range instead of downloading the same bytes four
times. IBM Plex Mono is static, so each weight is its own file.

Usage:  python3 scripts/fetch-fonts.py
Requires: curl. Re-run to refresh; output is deterministic.

IBM Plex is licensed under the SIL Open Font License 1.1.
"""

import os
import re
import subprocess
from collections import OrderedDict

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "fonts")
SUBSETS = ("latin", "latin-ext")   # everything the UI copy needs

SPECS = [
    ("IBM Plex Sans", "IBM+Plex+Sans:wght@400;500;600;700", "IBMPlexSans"),
    ("IBM Plex Mono", "IBM+Plex+Mono:wght@400;500;600",     "IBMPlexMono"),
]


def curl(url):
    return subprocess.run(
        ["curl", "-sS", "--fail", "-H", f"User-Agent: {UA}", url],
        capture_output=True, check=True).stdout


def main():
    os.makedirs(OUT, exist_ok=True)
    faces = []

    for family, query, slug in SPECS:
        css = curl(f"https://fonts.googleapis.com/css2?family={query}&display=swap").decode()
        blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css)

        groups = OrderedDict()
        for subset, block in blocks:
            if subset not in SUBSETS:
                continue
            url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
            weight = int(re.search(r"font-weight:\s*(\d+)", block).group(1))
            rng = re.search(r"unicode-range:\s*([^;]+);", block).group(1).strip()
            g = groups.setdefault((subset, url), {"weights": [], "range": rng})
            g["weights"].append(weight)

        for (subset, url), g in groups.items():
            lo, hi = min(g["weights"]), max(g["weights"])
            stem = f"{slug}-{lo}" if lo == hi else f"{slug}-{lo}-{hi}var"
            name = f"{stem}-{subset}.woff2"
            with open(os.path.join(OUT, name), "wb") as fh:
                fh.write(curl(url))
            size = os.path.getsize(os.path.join(OUT, name))
            faces.append((family, lo, hi, name, g["range"], size))
            span = f"{lo}" if lo == hi else f"{lo} {hi}"
            print(f"  {name:<32} weight {span:<9} {size:>6} B")

    lines = [
        "/* IBM Plex, self-hosted.",
        " *",
        " * Generated by scripts/fetch-fonts.py -- do not edit by hand.",
        " * Bundled into the Android APK and served from the website's own",
        " * origin, so typography works with no network and no request leaves",
        " * the device just to render the page. Latin + Latin-Extended only.",
        " *",
        " * IBM Plex is licensed under the SIL Open Font License 1.1.",
        " */",
        "",
    ]
    for family, lo, hi, name, rng, _ in faces:
        weight = f"{lo}" if lo == hi else f"{lo} {hi}"
        lines += [
            "@font-face {",
            f"  font-family: '{family}';",
            "  font-style: normal;",
            f"  font-weight: {weight};",
            "  font-display: swap;",
            f"  src: url('{name}') format('woff2');",
            f"  unicode-range: {rng};",
            "}",
            "",
        ]
    with open(os.path.join(OUT, "fonts.css"), "w") as fh:
        fh.write("\n".join(lines))

    total = sum(f[5] for f in faces)
    print(f"\n{len(faces)} faces, {total/1024:.0f} KB total -> fonts/fonts.css")


if __name__ == "__main__":
    main()
